---
title: "Final Project"
author: "Ben, Andrew, Pranati, Filip"
format: html
editor: source
---

## Setup
```{r setup}
library(tidyverse)
```

## Data
```{r}
CO2 <- read_csv("co2_emissions_tonnes_per_person.csv", col_select = c(1, 152:220))
mhi <- read_csv("mhhinc.csv", col_select = c(1, 152:220))

CO2 <- pivot_longer(CO2, cols = 2:70, names_to = "year", values_to = "co2")
mhi <- mhi %>% 
  mutate(
    across(.cols = `1950`:`2018`, .fns = ~ str_replace_all(
    string = .,
    pattern = "k(?<!\\.)\\b(\\d+(?:\\.\\d+)?)(?=k)\\b",
    replacement = "000")
    ),
    across(.cols = `1950`:`2018`, .fns = ~ str_replace_all(
    string = .,
    pattern = ".(\\d+)k",
    replacement = "\\100")
    )
    )


mhi <- mhi %>%
  mutate_at(vars(-1), function(x) {
    x <- ifelse(str_detect(x, "k"), 
                as.numeric(str_replace_all(x, "k", "")) * 1000, 
                as.numeric(x))
    return(x)
})

mhi <- mhi|>
  pivot_longer(cols = 2:70,
               names_to = "year",
               values_to = "mean_income",
  values_transform = list(mean_income = as.double))
```

